name: Gradle build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: temurin
          cache: gradle
      - name: Build project with Gradle
        run: chmod +x gradlew && ./gradlew build --no-daemon
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./build/reports/jacoco/test/
          fail_ci_if_error: true
          flags: unit_tests
          name: codecov-umbrella
          verbose: true
